config/routes.rb
Rails.application.routes.draw do
  resources :assignments
  resources :answers
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "up" => "rails/health#show", as: :rails_health_check

  namespace :api do
    namespace :v1 do
      resources :assignments, only: [:index] do
        resources :questions
      end
      resources :answers, only: [:create]
    end
  end
  root "home#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  belongs_to :assignment
  has_one :survey, through: :assignment
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :user
  belongs_to :survey
  has_many :questions, through: :survey

  scope :complete, ->{ where("completed_at is not null") }

  def self.ransackable_attributes(auth_object = nil)
    ["assigned_at", "completed_at", "created_at", "deadline_at", "id", "id_value", "survey_id", "updated_at", "user_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["survey", "user"]
  end

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :survey
  # has_many :assignments, through: :survey



  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "content", "updated_at", "position"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["survey"]
  end

end

app/models/survey.rb
class Survey < ApplicationRecord

  has_many :questions

  accepts_nested_attributes_for :questions, allow_destroy: true

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "name", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["questions"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :assignments

  accepts_nested_attributes_for :assignments


  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["assignments"]
  end
end

app/controllers/answers_controller.rb
class AnswersController < InheritedResources::Base

  private

    def answer_params
      params.require(:answer).permit(:user_id, :question_id, :assignment_id, :content)
    end

end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < ApplicationController
  protect_from_forgery with: :null_session

  def create
     @answer = Answer.build(answer_params)
     if @answer.save!
       if @answer.question.position == @answer.survey.questions.count
         @answer.assignment.touch(:completed_at)
       end
       head :no_content
     else
       render @answer
     end
  end

  private

  def answer_params
    params.require(:answer)
      .permit(:question_id, :assignment_id, :content)
      .merge(user_id: current_user.id)
  end

  def current_user
    User.first
  end

end

app/controllers/api/v1/assignments_controller.rb
class Api::V1::AssignmentsController < ApplicationController

  def index
    @assignments = Assignment.all.decorate
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < ApplicationController

  before_action :assignment

  def index
    @questions = @assignment.questions
  end


  def assignment
    @assignment = Assignment.find(params[:assignment_id])
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_form.html.haml
= form_for @answer do |f|
  - if @answer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@answer.errors.count, "error")} prohibited this answer from being saved:"
      %ul
        - @answer.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :question
    = f.text_field :question
  .field
    = f.label :assignment
    = f.text_field :assignment
  .field
    = f.label :content
    = f.textarea :content
  .actions
    = f.submit 'Save'

app/views/answers/edit.html.haml
%h1 Editing answer

= render 'form'

= link_to 'Show', @answer
\|
= link_to 'Back', answers_path

app/views/answers/index.html.haml
%h1 Listing answers

%table
  %thead
    %tr
      %th User
      %th Question
      %th Assignment
      %th Content
      %th
      %th
      %th

  %tbody
    - @answers.each do |answer|
      %tr
        %td= answer.user
        %td= answer.question
        %td= answer.assignment
        %td= answer.content
        %td= link_to 'Show', answer
        %td= link_to 'Edit', edit_answer_path(answer)
        %td= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Answer', new_answer_path

app/views/answers/new.html.haml
%h1 New answer

= render 'form'

= link_to 'Back', answers_path

app/views/answers/show.html.haml
%p#notice= notice

%p
  %b User:
  = @answer.user
%p
  %b Question:
  = @answer.question
%p
  %b Assignment:
  = @answer.assignment
%p
  %b Content:
  = @answer.content

= link_to 'Edit', edit_answer_path(@answer)
\|
= link_to 'Back', answers_path

app/views/home/index.html.haml
Welcome

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= content_for(:title) || "Surveyor"
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %meta{:content => "yes", :name => "apple-mobile-web-app-capable"}/
    %meta{:content => "yes", :name => "mobile-web-app-capable"}/
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    %link{:href => "/icon.png", :rel => "icon", :type => "image/png"}/
    %link{:href => "/icon.svg", :rel => "icon", :type => "image/svg+xml"}/
    %link{:href => "/icon.png", :rel => "apple-touch-icon"}/
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag :app, "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    %main.container.mx-auto.mt-28.px-5.flex
      = yield